version: '3.8'

services:
  TestTaskToOCS:
    image: "postgres:alpine3.19"
    restart: always
    container_name: TestTaskToOCS
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "CFPDataBase"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "15432:5432"